"""Generate or independently judge paraphrase candidates with append-only state.

Run ``--stage generate`` and ``--stage judge`` as separate processes so each
vLLM engine releases its GPU reservation before the other model is loaded.
Rejected pairs can be regenerated by increasing ``--attempt`` (up to the
configured maximum).  Accepted pairs are never regenerated.
"""

from __future__ import annotations

import argparse
import gc
import json
import re
from collections.abc import Mapping
from typing import Any

from src.common import (
    append_jsonl,
    batched,
    immutable_revision,
    load_jsonl,
    prompt_hash,
    read_yaml,
    resolve_path,
    utc_now,
)
from src.paraphrase_gates import deterministic_gates

CANDIDATE_PATH = "outputs/checkpoints/paraphrase_candidates.jsonl"
JUDGMENT_PATH = "outputs/checkpoints/paraphrase_judgments.jsonl"

TRANSFORMATION_INSTRUCTIONS = {
    "lexical_substitution": (
        "Replace wording with natural synonyms while retaining the same relations."
    ),
    "syntactic_restructuring": (
        "Substantially change the sentence structure without changing meaning."
    ),
    "clause_or_discourse_reordering": (
        "Reorder clauses or discourse while keeping every dependency clear."
    ),
    "constrained_free_paraphrase": (
        "Freely rewrite the wording while preserving all mathematical content."
    ),
    "voice_or_perspective_shift": (
        "Change voice or perspective without changing roles or quantities."
    ),
    "referential_restructuring": (
        "Change how entities are introduced and referred to while keeping roles exact."
    ),
    "compositional_restatement": "Recompose the statements into a different natural organization.",
}


def generation_prompt(original: str, transformation_type: str) -> str:
    instruction = TRANSFORMATION_INSTRUCTIONS[transformation_type]
    return f"""Rewrite the math word problem using the requested transformation.

Transformation: {transformation_type}
Specific instruction: {instruction}

Hard constraints:
- Preserve every number, unit, named-entity role, variable relationship, and requested unknown.
- Do not solve the problem, add hints, simplify the mathematical task, or delete details.
- Change only the linguistic realization.
- Return exactly one paraphrased problem and no explanation or quotation marks.

Original problem:
{original}
"""


def judge_prompt(original: str, candidate: str) -> str:
    return f"""You are a strict blinded semantic-equivalence auditor for math problems.
Determine whether the candidate asks exactly the same mathematical question as the original.
Check entity roles, all relationships, the requested target, implied constraints, and whether
the candidate adds a hint or makes the task easier. Do not solve either problem.

Return one JSON object only with this schema:
{{"equivalent": true, "uncertain": false, "target_preserved": true,
  "no_added_hint": true, "reason": "brief reason"}}

ORIGINAL:
{original}

CANDIDATE:
{candidate}
"""


def clean_candidate(text: str) -> str:
    value = text.strip()
    prefixes = ("Paraphrase:", "Paraphrased problem:", "Rewritten problem:")
    for prefix in prefixes:
        if value.lower().startswith(prefix.lower()):
            value = value[len(prefix) :].strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        value = value[1:-1].strip()
    return value


def render_instruction(tokenizer: Any, content: str) -> str:
    return tokenizer.apply_chat_template(
        [{"role": "user", "content": content}],
        tokenize=False,
        add_generation_prompt=True,
    )


def parse_judgment(text: str) -> dict[str, Any]:
    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if not match:
        return {"parse_ok": False, "uncertain": True, "raw": text}
    try:
        value = json.loads(match.group(0))
    except json.JSONDecodeError:
        return {"parse_ok": False, "uncertain": True, "raw": text}
    required = ("equivalent", "uncertain", "target_preserved", "no_added_hint")
    if any(not isinstance(value.get(field), bool) for field in required):
        return {"parse_ok": False, "uncertain": True, "raw": text}
    value["parse_ok"] = True
    value["raw"] = text
    return value


def pair_key(row: Mapping[str, Any]) -> tuple[str, str, str]:
    return str(row["dataset"]), str(row["item_id"]), str(row["form_id"])


def load_model(model_id: str, revision: str, gpu_memory_utilization: float):
    from transformers import AutoTokenizer
    from vllm import LLM

    tokenizer = AutoTokenizer.from_pretrained(model_id, revision=revision, trust_remote_code=True)
    llm = LLM(
        model=model_id,
        revision=revision,
        dtype="bfloat16",
        trust_remote_code=True,
        gpu_memory_utilization=gpu_memory_utilization,
        max_model_len=4096,
        generation_config="vllm",
    )
    return tokenizer, llm


def expected_pairs(config: Mapping[str, Any], split: str) -> list[dict[str, Any]]:
    manifest = [row for row in load_jsonl(config["manifest_path"]) if row["split"] == split]
    forms = [form for form in config["surface_forms"] if form["form_id"] != "original"]
    return [{**row, **form} for row in manifest for form in forms]


def run_generate(config: Mapping[str, Any], split: str, attempt: int, batch_size: int) -> None:
    settings = config["paraphrase_generation"]
    if not 1 <= attempt <= int(settings["max_attempts"]):
        raise ValueError(f"attempt must be within 1..{settings['max_attempts']}")
    accepted = {pair_key(row) for row in load_jsonl(config["paraphrases_path"])}
    prior_candidates = {(*pair_key(row), int(row["attempt"])) for row in load_jsonl(CANDIDATE_PATH)}
    work = [
        row
        for row in expected_pairs(config, split)
        if pair_key(row) not in accepted and (*pair_key(row), attempt) not in prior_candidates
    ]
    if not work:
        print(f"[paraphrase] no pending generation pairs for split={split} attempt={attempt}")
        return

    model_id = settings["generator_model"]
    revision = immutable_revision(
        settings.get("generator_revision"), model_id, "environment/model_revisions.json"
    )
    tokenizer, llm = load_model(model_id, revision, gpu_memory_utilization=0.88)
    from vllm import SamplingParams

    sampling = SamplingParams(
        n=1,
        temperature=float(settings["temperature"]),
        top_p=float(settings["top_p"]),
        max_tokens=int(settings["max_new_tokens"]),
        seed=int(settings["generation_seed"]) + attempt,
    )
    for batch in batched(work, batch_size):
        prompts = [
            render_instruction(
                tokenizer,
                generation_prompt(row["original_text"], row["transformation_type"]),
            )
            for row in batch
        ]
        outputs = llm.generate(prompts, sampling, use_tqdm=False)
        records = []
        for row, prompt, output in zip(batch, prompts, outputs, strict=True):
            text = clean_candidate(output.outputs[0].text)
            records.append(
                {
                    "dataset": row["dataset"],
                    "item_id": row["item_id"],
                    "split": row["split"],
                    "form_id": row["form_id"],
                    "transformation_type": row["transformation_type"],
                    "original_text": row["original_text"],
                    "paraphrase_text": text,
                    "generator_model": model_id,
                    "generator_revision": revision,
                    "prompt_hash": prompt_hash(prompt),
                    "seed": int(settings["generation_seed"]) + attempt,
                    "sampling_config": {
                        "temperature": settings["temperature"],
                        "top_p": settings["top_p"],
                        "max_new_tokens": settings["max_new_tokens"],
                    },
                    "attempt": attempt,
                    "automatic_gates": deterministic_gates(
                        row["original_text"], text, float(settings["min_normalized_edit_distance"])
                    ),
                    "created_at": utc_now(),
                }
            )
        append_jsonl(CANDIDATE_PATH, records)
        print(f"[paraphrase] generated {len(records)} candidates", flush=True)
    del llm
    gc.collect()


def run_judge(config: Mapping[str, Any], split: str, batch_size: int) -> None:
    settings = config["paraphrase_generation"]
    accepted = {pair_key(row) for row in load_jsonl(config["paraphrases_path"])}
    judged_attempts = {(*pair_key(row), int(row["attempt"])) for row in load_jsonl(JUDGMENT_PATH)}
    candidates = [
        row
        for row in load_jsonl(CANDIDATE_PATH)
        if row["split"] == split
        and pair_key(row) not in accepted
        and (*pair_key(row), int(row["attempt"])) not in judged_attempts
    ]
    if not candidates:
        print(f"[paraphrase] no pending judge candidates for split={split}")
        return

    deterministic_failures = [row for row in candidates if not row["automatic_gates"]["passed"]]
    if deterministic_failures:
        append_jsonl(
            JUDGMENT_PATH,
            [
                {
                    **{
                        key: row[key]
                        for key in ("dataset", "item_id", "split", "form_id", "attempt")
                    },
                    "accepted": False,
                    "judge_status": "automatic_gate_failed",
                    "automatic_gates": row["automatic_gates"],
                    "created_at": utc_now(),
                }
                for row in deterministic_failures
            ],
        )
    work = [row for row in candidates if row["automatic_gates"]["passed"]]
    if not work:
        return

    model_id = settings["judge_model"]
    revision = immutable_revision(
        settings.get("judge_revision"), model_id, "environment/model_revisions.json"
    )
    tokenizer, llm = load_model(model_id, revision, gpu_memory_utilization=0.88)
    from vllm import SamplingParams

    sampling = SamplingParams(n=1, temperature=0.0, max_tokens=256, seed=0)
    for batch in batched(work, batch_size):
        prompts = [
            render_instruction(
                tokenizer,
                judge_prompt(row["original_text"], row["paraphrase_text"]),
            )
            for row in batch
        ]
        outputs = llm.generate(prompts, sampling, use_tqdm=False)
        judgments = []
        newly_accepted = []
        for row, prompt, output in zip(batch, prompts, outputs, strict=True):
            parsed = parse_judgment(output.outputs[0].text)
            accepted_flag = bool(
                parsed.get("parse_ok")
                and parsed.get("equivalent")
                and not parsed.get("uncertain")
                and parsed.get("target_preserved")
                and parsed.get("no_added_hint")
            )
            status = "accepted" if accepted_flag else "rejected_or_uncertain"
            judgments.append(
                {
                    **{
                        key: row[key]
                        for key in ("dataset", "item_id", "split", "form_id", "attempt")
                    },
                    "accepted": accepted_flag,
                    "judge_status": status,
                    "judge_model": model_id,
                    "judge_revision": revision,
                    "judge_prompt_hash": prompt_hash(prompt),
                    "judgment": parsed,
                    "created_at": utc_now(),
                }
            )
            if accepted_flag:
                newly_accepted.append(
                    {
                        **row,
                        "paraphrase_generator": row.get(
                            "generator_model", settings["generator_model"]
                        ),
                        "judge_model": model_id,
                        "judge_revision": revision,
                        "judge_status": status,
                        "judge_result": parsed,
                        "accepted_at": utc_now(),
                    }
                )
        append_jsonl(JUDGMENT_PATH, judgments)
        append_jsonl(config["paraphrases_path"], newly_accepted)
        print(
            f"[paraphrase] judged {len(batch)} candidates; accepted {len(newly_accepted)}",
            flush=True,
        )
    del llm
    gc.collect()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="configs/experiment_main.yaml")
    parser.add_argument("--stage", choices=["generate", "judge"], required=True)
    parser.add_argument("--split", choices=["smoke", "pilot", "confirmatory"], required=True)
    parser.add_argument("--attempt", type=int, default=1)
    parser.add_argument("--batch-size", type=int, default=64)
    args = parser.parse_args()
    config = read_yaml(args.config)
    resolve_path(config["manifest_path"]).stat()
    if args.stage == "generate":
        run_generate(config, args.split, args.attempt, args.batch_size)
    else:
        run_judge(config, args.split, args.batch_size)


if __name__ == "__main__":
    main()
